### ISSUE TITLE
Don't set CPU limits

### ISSUE THREAD

**Issue by fmunteanu** [axivo/charts#230]
### Existing Issues

- [x] I have searched the existing issues

### Related Chart

ubuntu (application)

### What Happened

Resources should follow the following patterns:

```
resources:
  # -- (map) Resource limits for the container
  limits:
    # -- (string) Memory limit
    # @default -- "128Mi"
    memory: 128Mi
  # -- (map) Resource requests for the container
  requests:
    # -- (string) CPU request
    # @default -- "10m"
    cpu: 10m
    # -- (string) Memory request
    # @default -- "128Mi"
    memory: 128Mi
```

### Relevant Logs

```shell

```

### Code of Conduct

- [x] I agree to follow project's Code of Conduct
